---

- name: enable caddy
  service:
    name: caddy
    enabled: true

- name: restart caddy
  service:
    name: caddy
    state: restarted

- name: reload caddy
  service:
    name: caddy
    state: reloaded
