---

- hosts: proxmox_nodes
  gather_facts: false
  strategy: linear
  tags:
    - containers
  tasks:
    - name: delete containers
      include_tasks: ./tasks/delete_containers.yml
      loop: "{{ containers | default({}) | dict2items }}"
