---

# - hosts: proxmox_nodes
#   roles:
#     - common
#   tags:
#     - common

# TODO move this to common role
- hosts: proxmox_nodes
  gather_facts: false
  tasks:
    - name: create zfs pool
      command: zpool create -O compression=lz4 tank /dev/vdb -o ashift=12 creates=/tank
      become: true

    - name: create zfs datasets
      become: true
      community.general.zfs:
        name: "{{ item }}"
        state: present
      with_items:
        - tank/library
        - tank/library/movies
        - tank/library/series
        - tank/downloads

- hosts: proxmox_nodes
  gather_facts: false
  strategy: linear
  handlers:
    - name: sleep
      pause:
        seconds: 30
  tags:
    - containers
  tasks:
    - name: create containers
      include_tasks: ./tasks/create_containers.yml
      loop: "{{ containers | default({}) | dict2items }}"
    - meta: flush_handlers

- hosts: need_ansible_prep
  vars:
    ansible_user: root
  roles:
    - prep-for-ansible

- hosts: localhost
  tasks:
    - meta: refresh_inventory

- hosts: all,!proxmox_nodes,!mikrotik
  roles:
    - common

# - hosts: all,!proxmox_nodes,!mikrotik
#   become: true
#   collections:
#     - devsec.hardening
#   roles:
#     - devsec.hardening.os_hardening
#   tags:
#     - hardening

# - hosts: all,!mikrotik
#   become: true
#   collections:
#     - devsec.hardening
#   roles:
#     - devsec.hardening.ssh_hardening
#   tags:
#     - hardening

