---

- hosts: proxmox_nodes
  roles:
    - common
  tags:
    - common

# TODO move this to common role
- hosts: proxmox_nodes
  gather_facts: false
  tasks:
    - name: create zfs pool
      command: zpool create -O compression=lz4 tank /dev/vdb -o ashift=12 creates=/tank
      become: true

    - name: create zfs datasets
      become: true
      community.general.zfs:
        name: "{{ item }}"
        state: present
        extra_zfs_properties:
          acltype: posixacl
          xattr: sa
      with_items:
        - tank/library
        - tank/library/movies
        - tank/library/series
        - tank/library/animes
        - tank/apps
        - tank/apps/plex
        - tank/apps/prowlarr
        - tank/apps/radarr
        - tank/apps/sonarr
        - tank/apps/animarr
        - tank/downloads
        - tank/downloads/sabnzbd

    - name: set application permissions
      become: true
      file:
        state: directory
        path: "{{ item.path is defined | ternary(item.path, '/tank/apps/' + item.app) }}"
        owner: "{{ item.user | default(item.app) }}"
        group: "{{ item.group | default(item.app) }}"
        recurse: true
      loop:
        - app: prowlarr
        - app: animarr
        - app: animarr
          path: /tank/library/animes
        - app: sonarr
        - app: sonarr
          path: /tank/library/series
        - app: radarr
        - app: radarr
          path: /tank/library/movies
        - app: sabnzbd
        - app: sabnzbd
          path: /tank/downloads/sabnzbd
        - app: plex

- hosts: proxmox_nodes
  gather_facts: false
  strategy: linear
  handlers:
    - name: sleep
      pause:
        seconds: 10
  tags:
    - containers
  tasks:
    - include_tasks: ./tasks/create_containers.yml
      loop: "{{ containers | default({}) | dict2items }}"
    - meta: flush_handlers

- hosts: need_ansible_prep
  vars:
    ansible_user: root
    ansible_remote_tmp: /tmp/.root
  roles:
    - prep-for-ansible

- hosts: localhost
  tasks:
    - meta: refresh_inventory

- hosts: all,!proxmox_nodes,!mikrotik
  roles:
    - common
  tags:
    - common

# - hosts: all,!proxmox_nodes,!mikrotik
#   become: true
#   collections:
#     - devsec.hardening
#   roles:
#     - devsec.hardening.os_hardening
#   tags:
#     - hardening

# - hosts: all,!mikrotik
#   become: true
#   collections:
#     - devsec.hardening
#   roles:
#     - devsec.hardening.ssh_hardening
#   tags:
#     - hardening

