---

- import_playbook: mikrotik.yml
- import_playbook: proxmox.yml

- hosts: sabnzbd
  gather_facts: true
  roles:
    - sabnzbd

- hosts: radarr
  gather_facts: true
  roles:
    - radarr

- hosts: animarr,sonarr
  gather_facts: true
  roles:
    - sonarr

- hosts: prowlarr
  gather_facts: true
  roles:
    - prowlarr

- hosts: prowlarr,animarr,sonarr,radarr
  gather_facts: true
  roles:
    - servarr-config
  tags:
    - servarr
