---
- name: create containers
  delegate_to: localhost
  register: container
  notify:
    - sleep
  throttle: 1
  community.general.proxmox:
    vmid: "{{ item.value.vmid }}"
    node: pve
    api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
    proxmox_default_behavior: no_defaults
    timeout: 600
    onboot: true
    hostname: "{{ item.key }}"
    unprivileged: true
    storage: local-zfs
    netif:
      net0: 'name=eth0,bridge=vmbr0,ip=dhcp,ip6=dhcp,tag={{ item.value.vlan_tag }}'
    features:
      - nesting=1
    ostemplate: "{{ item.value.ostemplate | default(ostemplate) }}"
    pubkey: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: start containers
  delegate_to: localhost
  notify:
    - sleep
  community.general.proxmox:
    vmid: "{{ item.value.vmid }}"
    api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
    timeout: 600
    state: started

- name: add containers to `need_ansible_prep` group
  add_host:
    name: "{{ item.key }}"
    groups:
      - need_ansible_prep
  when:
    - container is changed

