---
- name: Prepare host for ansible
  vars:
    # ansible_user: root
    ansible_remote_tmp: /tmp/.root
  block:
    - name: Update APT cache
      apt:
        cache_valid_time: 86400
        update_cache: true
      ignore_errors: true

    - name: Install sudo
      apt:
        name: sudo
        state: present

    - name: Add ansible user
      user:
        name: ansible
        uid: 1100
        password_lock: true
        shell: /bin/bash

    - name: Add authorized keys for user "ansible"
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: https://github.com/kid.keys

    - name: Add user "ansible" to sudo
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0640
        create: true
        validate: 'visudo -cf %s'
