---

- name: install prerequisite
  become: true
  apt:
    cache_valid_time: 86400
    pkg:
      - curl
      - sqlite3

- name: create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: prowlarr
    group: prowlarr
  loop:
    - /var/lib/prowlarr

- name: get prowlarr version
  uri:
    url: "http://localhost:{{ prowlarr_port }}/initialize.js"
    return_content: true
  ignore_errors: true
  register: _prowlarr_version

- set_fact:
    current_prowlarr_version: "{{ _prowlarr_version.content | regex_search(\"version: '(?P<version>.+)'\", '\\g<version>') | first }}"
  when: _prowlarr_version is success

- name: install or update prowlarr
  block:
  - name: extract prowlarr
    unarchive:
      remote_src: yes
      src: "https://github.com/Prowlarr/Prowlarr/releases/download/v{{ prowlarr_version }}/Prowlarr.{{ prowlarr_branch }}.{{ prowlarr_version }}.linux-core-x64.tar.gz"
      dest: /opt/
      owner: prowlarr
      group: prowlarr
  when: current_prowlarr_version is not defined or current_prowlarr_version is version(prowlarr_version, '<')
  become: true
  tags:
    - install
  notify:
    - restart prowlarr
    - wait for start

- name: template systemd service
  become: true
  notify:
    - daemon-reload
    - enable prowlarr
    - restart prowlarr
  template:
    src: prowlarr.service.j2
    dest: /etc/systemd/system/prowlarr.service

- meta: flush_handlers

- name: get prowlarr init data
  uri:
    url: "http://localhost:{{ prowlarr_port }}/initialize.js"
    return_content: true
  ignore_errors: true
  register: _prowlarr_init_data
  tags:
    - facts

- set_fact:
    app_url: "{{ caddy_host is defined | ternary('https://' + caddy_host, 'http://' + ansible_fqdn + ':' + prowlarr_port | string) }}"
    api_root: "{{ _prowlarr_init_data.content | regex_search(\"apiRoot: '(?P<apiRoot>.+)'\", '\\g<apiRoot>') | first }}"
    api_key: "{{ _prowlarr_init_data.content | regex_search(\"apiKey: '(?P<apiKey>.+)'\", '\\g<apiKey>') | first }}"
  tags:
    - facts

- set_fact:
    api_url: "{{ app_url }}{{ api_root }}"
  tags:
    - facts
