---

- name: Setup DHCP pool
  routeros_command:
    commands:
      - '/ip pool add name="{{ item.routeros_if }}" ranges="{{ item.ipv4 | ipaddr("11") | ipaddr("address") }}-{{ item.ipv4 | ipaddr("254") | ipaddr("address") }}"'
  when:
    - item.dhcp is defined
    - item.dhcp
    - item.ipv4 is defined
  loop: "{{ interfaces }}"
  tags:
    - dhcp

- name: Setup DHCP network
  routeros_command:
    commands:
      - '/ip dhcp-server network add address="{{ item.ipv4 | ipaddr("0") }}" gateway="{{ item.ipv4 | ipaddr("1") | ipaddr("address") }}" dns-server="{{ item.ipv4 | ipaddr("1") | ipaddr("address") }}" domain="{{ item.desc }}.{{ top_level_domain }}"'
  when:
    - item.dhcp is defined
    - item.dhcp
    - item.ipv4 is defined
  loop: "{{ interfaces }}"
  tags:
    - dhcp

- name: Setup DHCP server
  routeros_command:
    commands:
      - '/ip dhcp-server add interface="{{ item.routeros_if }}" address-pool="{{ item.routeros_if }}" name="{{ item.desc }}" lease-time=1d'
  when:
    - item.dhcp is defined
    - item.dhcp
    - item.ipv4 is defined
  loop: "{{ interfaces }}"
  tags:
    - dhcp
