---

- name: configure mirrors
  replace:
    path: /etc/apt/sources.list
    regexp: '^deb http://archive.ubuntu.com/ubuntu (.*)$'
    replace: 'deb mirror://mirrors.ubuntu.com/mirrors.txt \g<1>'
  become: true
  notify:
    - apt update

- meta: flush_handlers

- name: Install gpg
  become: true
  apt:
    name: gpg
  when:
    - common_apt_keys

- name: Remove unwanted keys
  become: true
  apt_key:
    id: "{{ item }}"
    state: absent
  loop: "{{ common_apt_keys_remove }}"

- name: Add wanted keys
  become: true
  apt_key:
    id: "{{ item.id is defined | ternary(item.id, omit) }}"
    url: "{{ item.url is defined | ternary(item.url, omit) }}"
    keyserver: "{{ item.keyserver is defined | ternary(item.keyserver, omit) }}"
  loop: "{{ common_apt_keys }}"

- name: Remove unwanted packages repositories
  become: true
  apt_repository:
    repo: "{{ item.repo }}"
    state: absent
  loop: "{{ common_apt_repos_remove }}"

- name: Add packages repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ common_apt_repos }}"

- name: Remove unwanted packages
  become: true
  apt:
    name: "{{ common_packages_remove }}"
    force: true
    autoclean: true
    autoremove: true
    state: absent
- name: Update
  become: true
  apt:
    cache_valid_time: 86400
    update_cache: true

- name: Upgrade
  become: true
  apt:
    cache_valid_time: 86400
    upgrade: dist

- name: Install wanted packages
  become: true
  apt:
    cache_valid_time: 86400
    name: "{{ common_packages }}"

- name: Remove useless packages from the cache
  become: true
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes
