---

- import_tasks: apt.yml
  when: ansible_facts.distribution in ['Debian', 'Ubuntu']
  tags: apt

- user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    system: "{{ item.system | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
  with_items: "{{ common_users | default([]) }}"
  become: true

- lineinfile:
    path: "/etc/sudoers.d/{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    state: "{{ item.sudo | ternary('present', 'absent') }}"
    mode: 0440
    create: true
    validate: 'visudo -cf %s'
  with_items: "{{ common_users | default([]) }}"
  when: item.sudo is defined
  become: true

- ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.authorized_key }}"
  with_items: "{{ common_users | default([]) }}"
  when: item.authorized_key is defined
  become: true

- lineinfile:
    path: /etc/default/locale
    line: 'LANG=en_US.UTF-8'
    regexp: '^LANG='
    state: present
  become: true
  when: ansible_facts.distribution in ['Ubuntu']
