---

- name: set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}.{{ domain_name }}"

- name: create system groups
  become: true
  group:
    gid: "{{ item.gid is defined | ternary(item.gid + (common_gid_offset | default(0)), omit) }}"
    name: "{{ item.name }}"
    system: true
    state: present
  loop: "{{ common_system_groups | default([]) }}"

- name: create system users
  become: true
  user:
    uid: "{{ item.uid is defined | ternary(item.uid + (common_uid_offset | default(0)), omit) }}"
    name: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups is defined | ternary(item.groups | join(','), '')  }}"
    shell: "{{ item.shell | default('/usr/sbin/nologin') }}"
    system: true
    create_home: false
    state: present
  loop: "{{ common_system_users | default([]) }}"

# - name: add system usrs to groups
#   become: true
#   group:

- name: create regular users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    system: "{{ item.system | default(omit) }}"
    password_lock: "{{ item.password_lock | default(omit) }}"
  loop: "{{ common_users | default([]) }}"
  become: true

- lineinfile:
    path: "/etc/sudoers.d/{{ item.name }}"
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    state: "{{ item.sudo | ternary('present', 'absent') }}"
    mode: 0440
    create: true
    validate: 'visudo -cf %s'
  loop: "{{ common_users | default([]) }}"
  when: item.sudo is defined
  become: true

- ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.authorized_key }}"
  loop: "{{ common_users | default([]) }}"
  when: item.authorized_key is defined
  become: true

- lineinfile:
    path: /etc/default/locale
    line: 'LANG=en_US.UTF-8'
    regexp: '^LANG='
    state: present
  become: true
  when: ansible_facts.distribution in ['Ubuntu']

- import_tasks: apt.yml
  when: ansible_facts.distribution in ['Debian', 'Ubuntu']
  tags: apt
