---

ostemplate: local:vztmpl/ubuntu-21.04-standard_21.04-1_amd64.tar.gz

containers:
  plex:
    vmid: 100
    vlan_tag: 1030
  prowlarr:
    vmid:  110
    vlan_tag: 1030
  radarr:
    vmid: 120
    vlan_tag: 1030
  sonarr:
    vmid: 130
    vlan_tag: 1030
  animarr:
    vmid: 140
    vlan_tag: 1030
